# yaml-language-server: $schema=https://json.schemastore.org/semantic-release.json
---
branches:
    - master
    - name: alpha
      prerelease: true
      channel: alpha

plugins:
    - - '@semantic-release/commit-analyzer'
      - preset: conventionalcommits
        releaseRules:
            - type: docs
              scope: README
              release: patch

    - '@semantic-release/release-notes-generator'
    - - '@semantic-release/changelog'
      - changelogTitle: "# Changelog\n\nAll notable changes to this project will be documented in this file."
    - - '@semantic-release/exec'
      - publishCmd: yarn lerna version ${nextRelease.version} --no-git-tag-version --no-push --yes --exact && echo "true" > .release-created
    - - '@semantic-release/git'
      - assets:
            - 'package.json'
            - 'lerna.json'
            - 'CHANGELOG.md'
            - 'packages/*/package.json'
        message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
    - '@semantic-release/github'

preset: conventionalcommits
