/*
 * Copyright (c) 2020, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 */

export const extended = {
    // TODO (refactor): Inherit from recommended and deduplicate
    // ...recommended,
    runOnly: {
        type: 'rule',
        values: [
            'accesskeys',
            'area-alt',
            'aria-allowed-attr',
            'aria-allowed-role',
            'aria-hidden-body',
            'aria-hidden-focus',
            'aria-input-field-name',
            'aria-required-attr',
            'aria-required-children',
            'aria-required-parent',
            'aria-roledescription',
            'aria-roles',
            'aria-toggle-field-name',
            'aria-valid-attr-value',
            'aria-valid-attr',
            'audio-caption',
            'autocomplete-valid',
            'avoid-inline-spacing',
            'blink',
            'button-name',
            'bypass',
            'color-contrast',
            'css-orientation-lock',
            'definition-list',
            'dlitem',
            'document-title',
            'duplicate-id-active',
            'duplicate-id-aria',
            'duplicate-id',
            'empty-heading',
            'focus-order-semantics',
            'form-field-multiple-labels',
            'frame-tested',
            'frame-title',
            'heading-order',
            'html-has-lang',
            'html-lang-valid',
            'html-xml-lang-mismatch',
            'identical-links-same-purpose',
            'image-alt',
            'image-redundant-alt',
            'input-button-name',
            'input-image-alt',
            'label-title-only',
            'label',
            'landmark-banner-is-top-level',
            'landmark-complementary-is-top-level',
            'landmark-contentinfo-is-top-level',
            'landmark-main-is-top-level',
            'landmark-no-duplicate-banner',
            'landmark-no-duplicate-contentinfo',
            'landmark-no-duplicate-main',
            'landmark-one-main',
            'landmark-unique',
            'link-in-text-block',
            'link-name',
            'list',
            'listitem',
            'marquee',
            'meta-refresh',
            'meta-viewport-large',
            'meta-viewport',
            'no-autoplay-audio',
            'object-alt',
            'p-as-heading',
            'page-has-heading-one',
            'region',
            'role-img-alt',
            'scope-attr-valid',
            'scrollable-region-focusable',
            'server-side-image-map',
            'svg-img-alt',
            'tabindex',
            'td-has-header',
            'td-headers-attr',
            'th-has-data-cells',
            'valid-lang',
            'video-caption',
        ],
    },
    resultTypes: ['violations'],
};
