name: PR Title Linter

on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: yarn ci:build
            - uses: JulienKode/pull-request-name-linter-action@v0.1.2
